"""empty message

Revision ID: 29791f08941d
Revises: 90a532a66621
Create Date: 2023-11-03 08:26:34.437673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29791f08941d'
down_revision = '90a532a66621'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_list',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codenumber', sa.String(length=50), nullable=True),
    sa.Column('stockname', sa.String(length=50), nullable=True),
    sa.Column('markettag', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codenumber'),
    sa.UniqueConstraint('stockname')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_list')
    # ### end Alembic commands ###
