"""empty message

Revision ID: 47034b546340
Revises: 47dc4deb5493
Create Date: 2023-11-09 14:27:16.718338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47034b546340'
down_revision = '47dc4deb5493'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('mobile_number', sa.String(length=20), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('_password', sa.String(length=120), nullable=True),
    sa.Column('signature', sa.String(length=255), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('is_internal_employee', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('mobile_number'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
