"""empty message

Revision ID: 47dc4deb5493
Revises: feb044beb666
Create Date: 2023-11-08 14:08:26.450928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47dc4deb5493'
down_revision = 'feb044beb666'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('SECURITY_CODE', sa.String(length=50), nullable=True),
    sa.Column('SECURITY_NAME_ABBR', sa.String(length=50), nullable=True),
    sa.Column('INCOME_datajson', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('SECURITY_CODE')
    )
    op.create_table('stock_database',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('SECURITY_CODE', sa.String(length=50), nullable=True),
    sa.Column('SECURITY_NAME_ABBR', sa.String(length=50), nullable=True),
    sa.Column('PRICE_datajson', sa.JSON(), nullable=True),
    sa.Column('INCOME_datajson', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('SECURITY_CODE')
    )
    op.create_table('stock_income',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('SECURITY_CODE', sa.String(length=50), nullable=True),
    sa.Column('SECURITY_NAME_ABBR', sa.String(length=50), nullable=True),
    sa.Column('INCOME_datajson', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('SECURITY_CODE')
    )
    op.create_table('stock_list',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('SECURITY_CODE', sa.String(length=50), nullable=True),
    sa.Column('SECURITY_NAME_ABBR', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('SECURITY_CODE')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_list')
    op.drop_table('stock_income')
    op.drop_table('stock_database')
    op.drop_table('stock_data')
    # ### end Alembic commands ###
