"""empty message

Revision ID: 90a532a66621
Revises: b8258aebd1da
Create Date: 2023-11-02 17:00:43.874614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90a532a66621'
down_revision = 'b8258aebd1da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codenumber', sa.String(length=50), nullable=True),
    sa.Column('stockname', sa.String(length=50), nullable=True),
    sa.Column('markettag', sa.String(length=50), nullable=True),
    sa.Column('datajson', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codenumber'),
    sa.UniqueConstraint('stockname')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_data')
    # ### end Alembic commands ###
