"""empty message

Revision ID: b8258aebd1da
Revises: 
Create Date: 2023-11-02 11:22:47.483058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8258aebd1da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codenumber', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(None, ['codenumber'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('codenumber')

    # ### end Alembic commands ###
