"""empty message

Revision ID: f60c160fd797
Revises: 2f2aedcefd0b
Create Date: 2023-11-07 11:13:44.279952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f60c160fd797'
down_revision = '2f2aedcefd0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_income',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('SECURITY_CODE', sa.String(length=50), nullable=True),
    sa.Column('SECURITY_NAME_ABBR', sa.String(length=50), nullable=True),
    sa.Column('INCOME_datajson', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('SECURITY_CODE')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_income')
    # ### end Alembic commands ###
