"""empty message

Revision ID: f889ea8a9846
Revises: aa6a64c9842e
Create Date: 2023-11-03 14:24:44.252845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f889ea8a9846'
down_revision = 'aa6a64c9842e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_list', schema=None) as batch_op:
        batch_op.drop_index('SECURITY_NAME_ABBR')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_list', schema=None) as batch_op:
        batch_op.create_index('SECURITY_NAME_ABBR', ['SECURITY_NAME_ABBR'], unique=False)

    # ### end Alembic commands ###
