"""empty message

Revision ID: feb044beb666
Revises: 6c5d0be061d6
Create Date: 2023-11-08 10:22:27.181580

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'feb044beb666'
down_revision = '6c5d0be061d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_database',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('SECURITY_CODE', sa.String(length=50), nullable=True),
    sa.Column('SECURITY_NAME_ABBR', sa.String(length=50), nullable=True),
    sa.Column('PRICE_datajson', sa.JSON(), nullable=True),
    sa.Column('INCOME_datajson', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('SECURITY_CODE')
    )
    with op.batch_alter_table('stock_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('INCOME_datajson', sa.JSON(), nullable=True))
        batch_op.drop_column('datajson')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datajson', mysql.JSON(), nullable=True))
        batch_op.drop_column('INCOME_datajson')

    op.drop_table('stock_database')
    # ### end Alembic commands ###
